### ISSUE TITLE
Add support for gapless playback

### ISSUE THREAD

**Issue by jcass77** [mopidy/mopidy-pandora#13]
Gapless playback will be a nice feature to add, especially seeing as the high quality Pandora streams can take a while to buffer between track changes.

Mopidy 1.0.5 contains the basic callback mechanism for the implementation, but it still does not handle buffering properly. More info is available at: https://discuss.mopidy.com/t/has-the-gapless-playback-implementation-been-completed-yet/784/2

Perhaps this is something that we can take a look at when gapless playback is delivered in Mopidy 1.x

**Comment by jcass77** [comment]
The relevant Mopidy issue that will make this feature possible seems to be: https://github.com/mopidy/mopidy/issues/668

**Comment by jcass77** [comment]
The way this has been implemented in Mopidy 2.0, it does not appear as if there is anything more for backends to do in order to enable gapless playback - it works for all backends out of the box.

**Comment by ErwinP** [comment]
Hi,

Sorry to post in this closed issue, but I'm having problems with the gmusic component. I'm streaming to a chromecast using icecast2, and always get a disconnection when a next song is about to be played. I assume that this is due to the fact that the stream still gets interrupted, despite that I'm on mopidy v 2.1.0.

Is there anything that can be done about this?

Thank you in advance,
Erwin
